
[general]
	disable_mod = false
	hide_bossbar = true
	shadow_text = true
	auto_start = false
	animationSpeed = 1.0
	hide_debug_crosshair = false
	background_color = 1867534416
	space_modules = false
	always_show_profiler = false
	animations = true
	fontScale = 1.0
	hide_sidebar = true
	always_show_tps = false

[[modules_right]]
	name = "graphics"
	name_color = 9506889
	value_color = 10824234
	enabled = true

	[modules_right.lines]
		shader = true
		render_distance = true
		graphics = true
		clouds = true
		biome_blend_radius = true

[[modules_left]]
	color_high = 7605562
	color_med = 10551367
	name = "fps"
	enabled = true
	color_low = 11867227

	[modules_left.lines]
		fps = true

[[modules_left]]
	color_x = 11867227
	color_y = 11867227
	color_z = 11867227
	name = "coords"
	name_color = 16733525
	enabled = true

	[modules_left.lines]
		chunk_coords = false
		player_coords = true
		block_coords = false
		chunk_relative_coords = false

